---
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: filebeat
spec:
  type: filebeat
  version: 7.10.1
  elasticsearchRef:
    name: elasticsearch-monitoring
  kibanaRef:
    name: kibana-monitoring
  config:
    filebeat.autodiscover.providers:
    - type: kubernetes
      node: ${NODE_NAME}
      hints:
        enabled: true
        default_config:
          type: container
          paths:
          - /var/log/containers/*${data.kubernetes.container.id}.log

      templates:
      - condition.equals.kubernetes.labels.app: "mongodb"
        config:
        - module: mongodb
          log.input:
            type: container
            paths: ["/var/log/containers/*${data.kubernetes.container.id}.log"]

      - condition.equals.kubernetes.labels.app: "postgresql"
        config:
        - module: postgresql
          log.input:
            type: container
            paths: ["/var/log/containers/*${data.kubernetes.container.id}.log"]

      - condition.equals.kubernetes.labels.app: "redis"
        config:
        - module: redis
          log.input:
            type: container
            paths: ["/var/log/containers/*${data.kubernetes.container.id}.log"]

      - condition.equals.kubernetes.labels.app: "kafka"
        config:
        - module: kafka
          log.input:
            type: container
            paths: ["/var/log/containers/*${data.kubernetes.container.id}.log"]

      - condition.equals.kubernetes.labels.app: "kibana"
        config:
        - module: kibana
          log.input:
            type: container
            paths: ["/var/log/containers/*${data.kubernetes.container.id}.log"]

    processors:
    - add_cloud_metadata: {}
    - add_host_metadata: {}
    logging.json: true
  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: filebeat
        automountServiceAccountToken: true
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true
        securityContext:
          runAsUser: 0
        containers:
        - name: filebeat
          volumeMounts:
          - name: varlogcontainers
            mountPath: /var/log/containers
          - name: varlogpods
            mountPath: /var/log/pods
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
        volumes:
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: varlibnutanixdockercontainers
          hostPath:
            path: /var/nutanix/docker/containers
...