---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-monitoring
spec:
  version: 7.9.3
  nodeSets:
  - name: default
    count: 3
    config:
      node.store.allow_mmap: false

---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-monitoring
spec:
  version: 7.9.3
  count: 1
  elasticsearchRef:
    name: elasticsearch-monitoring
  config:
    xpack.monitoring.ui.container.elasticsearch.enabled: true

...